# Generated by Django 3.2.15 on 2022-08-16 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='title')),
                ('source_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='source id')),
                ('source_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='source name')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='author')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('url_to_image', models.URLField(blank=True, null=True, verbose_name='url to image')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
    ]
